FROM nginx:latest

COPY nginx.conf     /etc/nginx/conf.d/default.conf
COPY /certs_nginx/fullchain.pem /etc/letsencrypt/fullchain.pem
COPY /certs_nginx/privkey.pem   /etc/letsencrypt/privkey.pem
# COPY /html/login.php     /var/www/html/login.php
# COPY /html/register.php  /var/www/html/register.php
# COPY /html/welcome.php   /var/www/html/welcome.php
# COPY /html/db.php     /var/www/html/db.php
